services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'example'
      MYSQL_DATABASE: 'testdb'
      # MYSQL_USER: 'root'
      # MYSQL_PASSWORD: 'example'
    ports:
      - '3307:3306'
    # volumes:
    #   - mysql-data:/var/lib/mysql
  # mysql1:
  #   image: mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 'example'
  #     MYSQL_DATABASE: 'testdb'
  # MYSQL_USER: 'root'
  # MYSQL_PASSWORD: 'example'
  # ports:
  #   - '3307:3306'
  # volumes:
  #   - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - '8080:8080'
    depends_on:
      - mysql

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    environment:
      - REDIS_PASSWORD=example
    ports:
      - 6379:6379
  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - 8001:8001
    volumes:
      - redis_insight_volume_data:/db
volumes:
  redis_volume_data:
  redis_insight_volume_data:
